apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Authentication
  template:
    metadata:
      labels:
        app: Authentication
    spec:
      containers:
      - name: Authenticationrepos
        image: retail_banking_system_cr.azurecr.io/Authenticationrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Authentication